all:
	gcc free.c init.c test_malloc.c test_malloc_internal.c find_free_block.c malloc_large.c malloc_init.c  ../*.c -I ~/.brew/include -lcriterion -L ~/.brew/lib -lft -L ../libft/ -I ../libft/includes
	./a.out
